name: SwiftCI

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - '*'

jobs:
  testing_macos:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v1
    - name: "Xcode13 iOS"
      run:  xcodebuild clean test -project CardInfo.xcodeproj -scheme Test-iOS -sdk iphonesimulator -destination "platform=iOS Simulator,OS=15.0,name=iPhone 8" -configuration Debug
